---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /volume2/Home_Media/apps/radarr/config:/config
      - /volume2/Home_Media/streaming/movies:/movies #optional
      - /volume2/Home_Media/streaming/torrent:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /volume2/Home_Media/apps/sonarr/config:/config
      - /volume2/Home_Media/streaming/tv:/tv #optional
      - /volume2/Home_Media/streaming/torrent:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:0.22.1524
    container_name: jackett
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - /volume2/Home_Media/apps/jackett/config:/config
      - /volume2/Home_Media/streaming/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  readarr:
      image: lscr.io/linuxserver/readarr:develop
      container_name: readarr
      environment:
        - PUID=1027
        - PGID=100
        - TZ=Europe/Madrid
      volumes:
        - /volume2/Home_Media/apps/readarr/config:/config
        - /volume2/Home_Media/apps/readarr/data/books:/books #optional
        - /volume2/Home_Media/streaming/torrent:/downloads #optional
      ports:
        - 8787:8787
      restart: unless-stopped 
  transmission:
    image: lscr.io/linuxserver/transmission:4.0.6
    container_name: transmission
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /volume2/Home_Media/apps/transmission/config:/config
      - /volume2/Home_Media/streaming/torrent:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Madrid
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 